### ISSUE TITLE
NoSuchMethodError with latest 0.10.0 version (as defined in README.md)

### ISSUE THREAD

**Issue by jentfoo** [mboudreau/Alternator#92]
I was attempting to use your library but I must be doing something wrong.  I seem to get this when I attempt to construct the AlternatorDBClientV2:

java.lang.NoSuchMethodError: com.michelboudreau.alternatorv2.AlternatorDBClientV2.setConfiguration(Lcom/amazonaws/ClientConfiguration;)V
	at com.michelboudreau.alternatorv2.AlternatorDBClientV2.init(AlternatorDBClientV2.java:130)
	at com.michelboudreau.alternatorv2.AlternatorDBClientV2.<init>(AlternatorDBClientV2.java:106)
	at com.michelboudreau.alternatorv2.AlternatorDBClientV2.<init>(AlternatorDBClientV2.java:101)

Any suggestions?

**Comment by mboudreau** [comment]
It's a bit hard to debug if I don't know how you've set it up. Can you
paste your configuration?

**Comment by jentfoo** [comment]
I am actually using the default constructor (so no configuration provided).  The example in the README.md produces it exactly.

Here is my test code exactly:
https://gist.github.com/jentfoo/7d72f04f47798c6e646b

I am using amazon aws sdk 1.10.2

**Comment by mboudreau** [comment]
Hm, to be frank, I haven't used alternator in a while. Could be a change in
the SDK that hasn't been implemented in the mock service.

It would be awesome if you can debug it and submit a pull request with the
fix. Cheers.

**Comment by rrutt** [comment]
See the above Pull Request https://github.com/mboudreau/Alternator/pull/93 for revisions to compile and/or run with AWS SDK 1.10.2

If you need to work with this before the Pull Request can be merged into the 'master' branch, obtain the revision from my GitHub repository here: https://github.com/rrutt/Alternator/tree/aws-sdk-1.10.2

**Comment by jentfoo** [comment]
Awesome, thank you @rrutt

**Comment by jentfoo** [comment]
I see #93 has been merged.  Is there any plans to release an artifact with that fix?

**Comment by jentfoo** [comment]
Sorry, never mind.  It just goes on to another failure (this time NoSuchField requestHandler2s).  I will see if I can make a PR for you

**Comment by jentfoo** [comment]
So I am not sure what the issue is.  In eclipse I get NoSuchFieldError as described above.  But when I go into the amazon code I have checked out, that field is absolutely there.  So I am not sure what is going on in eclipse.  And sadly without a published artifact (at least as a snapshot) I am not sure how to test these changes without eclipse.

So would it be possible to get an artifact for me to test against?

**Comment by mboudreau** [comment]
@jentfoo Yes, sorry, didn't think to deploy a new artefact version.  I'll do that.

**Comment by jentfoo** [comment]
@mboudreau Did you deploy the artifact?  I looked on sonatype and don't see a 0.10.1-SNAPSHOT or a 0.10.1 artifact released.

What should the maven URL be for your snapshot artifacts?

**Comment by mboudreau** [comment]
@jentfoo Alright, I've release version 0.11.0.  Sorry for the delay in doing so.  Please try it out to see if it works.

Cheers.

**Comment by jentfoo** [comment]
Thanks for the new artifact!  Closing this since this appears to be fixed (but I will be opening a new issue shortly)
